version: "3"

services:
    poppi-bot:
        image: pierrezemb/gostatic
        ports:
            - 8043:8044
        volumes:
            - ./:/srv/http
        networks:
            -  proxy_net

networks:
    proxy_net:
        external: true
